export const constants = {
    fileNames: {
        animation: 'animation',
        main: 'play.mcfunction',
        music: 'music',
        tickDir: 'tick',
        track: {
            dir: 'track',
            fileName: 'track.mcfunction',
            name: 'track',
        },
    },
    instrumentToBlock: {
        0: 'minecraft:dirt',
        1: 'minecraft:oak_log',
        2: 'minecraft:cobblestone',
        3: 'minecraft:sand',
        4: 'minecraft:glass',
        5: 'minecraft:white_wool',
        6: 'minecraft:clay',
        7: 'minecraft:gold_block',
        8: 'minecraft:packed_ice',
        9: 'minecraft:bone_block',
        10: 'minecraft:iron_block',
        11: 'minecraft:soul_sand',
        12: 'minecraft:pumpkin',
        13: 'minecraft:emerald_block',
        14: 'minecraft:hay_block',
        15: 'minecraft:glowstone',
    },
    instrumentToCommand: {
        0: 'harp',
        1: 'bass',
        2: 'basedrum',
        3: 'snare',
        4: 'hat',
        5: 'guitar',
        6: 'flute',
        7: 'bell',
        8: 'chime',
        9: 'xylophone',
        10: 'iron_xylophone',
        11: 'cow_bell',
        12: 'didgeridoo',
        13: 'bit',
        14: 'banjo',
        15: 'pling',
    },
    instrumentToGlass: {
        0: 'minecraft:green_stained_glass',
        1: 'minecraft:brown_stained_glass',
        2: 'minecraft:pink_stained_glass',
        3: 'minecraft:purple_stained_glass',
        4: 'minecraft:white_stained_glass',
        5: 'minecraft:orange_stained_glass',
        6: 'minecraft:yellow_stained_glass',
        7: 'minecraft:red_stained_glass',
        8: 'minecraft:light_blue_stained_glass',
        9: 'minecraft:light_gray_stained_glass',
        10: 'minecraft:cyan_stained_glass',
        11: 'minecraft:blue_stained_glass',
        12: 'minecraft:gray_stained_glass',
        13: 'minecraft:lime_stained_glass',
        14: 'minecraft:magenta_stained_glass',
        15: 'minecraft:black_stained_glass',
    },
    nbs: {
        maxFramesPerSecond: 20 * 100,
        octaveStart: 33,
    },
    worlds: {
        end: 'minecraft:the_end',
        nether: 'minecraft:nether',
        world: 'minecraft:world',
    },
};
